/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {List400Error}
 */
// @ts-ignore
export function createList400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoList400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {List403Error}
 */
// @ts-ignore
export function createList403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoList403Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {List404Error}
 */
// @ts-ignore
export function createList404ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoList404Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {List422Error}
 */
// @ts-ignore
export function createList422ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoList422Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {List500Error}
 */
// @ts-ignore
export function createList500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoList500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ListPostResponse_data}
 */
// @ts-ignore
export function createListPostResponse_dataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoListPostResponse_data;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ListPostResponse}
 */
// @ts-ignore
export function createListPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoListPostResponse;
}
/**
 * The deserialization information for the current model
 * @param List400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoList400Error(list400Error: Partial<List400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { list400Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { list400Error.messageEscaped = n.getStringValue(); },
        "success": n => { list400Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param List403Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoList403Error(list403Error: Partial<List403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { list403Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { list403Error.messageEscaped = n.getStringValue(); },
        "success": n => { list403Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param List404Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoList404Error(list404Error: Partial<List404Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { list404Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { list404Error.messageEscaped = n.getStringValue(); },
        "success": n => { list404Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param List422Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoList422Error(list422Error: Partial<List422Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { list422Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { list422Error.messageEscaped = n.getStringValue(); },
        "success": n => { list422Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param List500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoList500Error(list500Error: Partial<List500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { list500Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { list500Error.messageEscaped = n.getStringValue(); },
        "success": n => { list500Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ListPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoListPostResponse(listPostResponse: Partial<ListPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { listPostResponse.data = n.getCollectionOfObjectValues<ListPostResponse_data>(createListPostResponse_dataFromDiscriminatorValue); },
        "message": n => { listPostResponse.message = n.getStringValue(); },
        "success": n => { listPostResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ListPostResponse_data The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoListPostResponse_data(listPostResponse_data: Partial<ListPostResponse_data> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "assignees": n => { listPostResponse_data.assignees = n.getCollectionOfPrimitiveValues<string>(); },
        "body": n => { listPostResponse_data.body = n.getStringValue(); },
        "closedAt": n => { listPostResponse_data.closedAt = n.getStringValue(); },
        "createdAt": n => { listPostResponse_data.createdAt = n.getStringValue(); },
        "issueNumber": n => { listPostResponse_data.issueNumber = n.getNumberValue(); },
        "issueUrl": n => { listPostResponse_data.issueUrl = n.getStringValue(); },
        "labels": n => { listPostResponse_data.labels = n.getCollectionOfPrimitiveValues<string>(); },
        "state": n => { listPostResponse_data.state = n.getEnumValue<ListPostResponse_data_state>(ListPostResponse_data_stateObject); },
        "title": n => { listPostResponse_data.title = n.getStringValue(); },
        "updatedAt": n => { listPostResponse_data.updatedAt = n.getStringValue(); },
    }
}
export interface List400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface List403Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface List404Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface List422Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface List500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface ListPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: ListPostResponse_data[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface ListPostResponse_data extends AdditionalDataHolder, Parsable {
    /**
     * The assignees property
     */
    assignees?: string[] | null;
    /**
     * The body property
     */
    body?: string | null;
    /**
     * The closedAt property
     */
    closedAt?: string | null;
    /**
     * The createdAt property
     */
    createdAt?: string | null;
    /**
     * The issueNumber property
     */
    issueNumber?: number | null;
    /**
     * The issueUrl property
     */
    issueUrl?: string | null;
    /**
     * The labels property
     */
    labels?: string[] | null;
    /**
     * The state property
     */
    state?: ListPostResponse_data_state | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: string | null;
}
export type ListPostResponse_data_state = (typeof ListPostResponse_data_stateObject)[keyof typeof ListPostResponse_data_stateObject];
/**
 * Builds and executes requests for operations under /issue/list
 */
export interface ListRequestBuilder extends BaseRequestBuilder<ListRequestBuilder> {
    /**
     * 指定のリポジトリに対して Issue 一覧を取得し、JSON として返却する。
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ListPostResponse>}
     * @throws {List400Error} error when the service returns a 400 status code
     * @throws {List403Error} error when the service returns a 403 status code
     * @throws {List404Error} error when the service returns a 404 status code
     * @throws {List422Error} error when the service returns a 422 status code
     * @throws {List500Error} error when the service returns a 500 status code
     */
     post(requestConfiguration?: RequestConfiguration<ListRequestBuilderPostQueryParameters> | undefined) : Promise<ListPostResponse | undefined>;
    /**
     * 指定のリポジトリに対して Issue 一覧を取得し、JSON として返却する。
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<ListRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * 指定のリポジトリに対して Issue 一覧を取得し、JSON として返却する。
 */
export interface ListRequestBuilderPostQueryParameters {
    state?: PostStateQueryParameterType;
}
export type PostStateQueryParameterType = (typeof PostStateQueryParameterTypeObject)[keyof typeof PostStateQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param List400Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeList400Error(writer: SerializationWriter, list400Error: Partial<List400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!list400Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", list400Error.data);
    writer.writeStringValue("message", list400Error.messageEscaped);
    writer.writeBooleanValue("success", list400Error.success);
    writer.writeAdditionalData(list400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param List403Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeList403Error(writer: SerializationWriter, list403Error: Partial<List403Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!list403Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", list403Error.data);
    writer.writeStringValue("message", list403Error.messageEscaped);
    writer.writeBooleanValue("success", list403Error.success);
    writer.writeAdditionalData(list403Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param List404Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeList404Error(writer: SerializationWriter, list404Error: Partial<List404Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!list404Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", list404Error.data);
    writer.writeStringValue("message", list404Error.messageEscaped);
    writer.writeBooleanValue("success", list404Error.success);
    writer.writeAdditionalData(list404Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param List422Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeList422Error(writer: SerializationWriter, list422Error: Partial<List422Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!list422Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", list422Error.data);
    writer.writeStringValue("message", list422Error.messageEscaped);
    writer.writeBooleanValue("success", list422Error.success);
    writer.writeAdditionalData(list422Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param List500Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeList500Error(writer: SerializationWriter, list500Error: Partial<List500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!list500Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", list500Error.data);
    writer.writeStringValue("message", list500Error.messageEscaped);
    writer.writeBooleanValue("success", list500Error.success);
    writer.writeAdditionalData(list500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ListPostResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeListPostResponse(writer: SerializationWriter, listPostResponse: Partial<ListPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!listPostResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ListPostResponse_data>("data", listPostResponse.data, serializeListPostResponse_data);
    writer.writeStringValue("message", listPostResponse.message);
    writer.writeBooleanValue("success", listPostResponse.success);
    writer.writeAdditionalData(listPostResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ListPostResponse_data The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeListPostResponse_data(writer: SerializationWriter, listPostResponse_data: Partial<ListPostResponse_data> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!listPostResponse_data || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("assignees", listPostResponse_data.assignees);
    writer.writeStringValue("body", listPostResponse_data.body);
    writer.writeStringValue("closedAt", listPostResponse_data.closedAt);
    writer.writeStringValue("createdAt", listPostResponse_data.createdAt);
    writer.writeNumberValue("issueNumber", listPostResponse_data.issueNumber);
    writer.writeStringValue("issueUrl", listPostResponse_data.issueUrl);
    writer.writeCollectionOfPrimitiveValues<string>("labels", listPostResponse_data.labels);
    writer.writeEnumValue<ListPostResponse_data_state>("state", listPostResponse_data.state);
    writer.writeStringValue("title", listPostResponse_data.title);
    writer.writeStringValue("updatedAt", listPostResponse_data.updatedAt);
    writer.writeAdditionalData(listPostResponse_data.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ListRequestBuilderUriTemplate = "{+baseurl}/issue/list{?state*}";
export const ListPostResponse_data_stateObject = {
    Open: "open",
    Closed: "closed",
} as const;
/**
 * Metadata for all the requests in the request builder.
 */
export const ListRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ListRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createList400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createList403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createList404ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createList422ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createList500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createListPostResponseFromDiscriminatorValue,
    },
};
export const PostStateQueryParameterTypeObject = {
    Open: "open",
    Closed: "closed",
    All: "all",
} as const;
/* tslint:enable */
/* eslint-enable */
