/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePaths400Error_errors}
 */
// @ts-ignore
export function createDownloadFilePaths400Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePaths400Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePaths400Error}
 */
// @ts-ignore
export function createDownloadFilePaths400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePaths400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePaths422Error_errors}
 */
// @ts-ignore
export function createDownloadFilePaths422Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePaths422Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePaths422Error}
 */
// @ts-ignore
export function createDownloadFilePaths422ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePaths422Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePaths429Error_errors}
 */
// @ts-ignore
export function createDownloadFilePaths429Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePaths429Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePaths429Error}
 */
// @ts-ignore
export function createDownloadFilePaths429ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePaths429Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePaths500Error_errors}
 */
// @ts-ignore
export function createDownloadFilePaths500Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePaths500Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePaths500Error}
 */
// @ts-ignore
export function createDownloadFilePaths500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePaths500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePathsPostRequestBody}
 */
// @ts-ignore
export function createDownloadFilePathsPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePathsPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePathsPostResponse_files}
 */
// @ts-ignore
export function createDownloadFilePathsPostResponse_filesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePathsPostResponse_files;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilePathsPostResponse}
 */
// @ts-ignore
export function createDownloadFilePathsPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilePathsPostResponse;
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePaths400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePaths400Error(downloadFilePaths400Error: Partial<DownloadFilePaths400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { downloadFilePaths400Error.detail = n.getStringValue(); },
        "errors": n => { downloadFilePaths400Error.errors = n.getObjectValue<DownloadFilePaths400Error_errors>(createDownloadFilePaths400Error_errorsFromDiscriminatorValue); },
        "instance": n => { downloadFilePaths400Error.instance = n.getStringValue(); },
        "status": n => { downloadFilePaths400Error.status = n.getNumberValue(); },
        "title": n => { downloadFilePaths400Error.title = n.getStringValue(); },
        "type": n => { downloadFilePaths400Error.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePaths400Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePaths400Error_errors(downloadFilePaths400Error_errors: Partial<DownloadFilePaths400Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePaths422Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePaths422Error(downloadFilePaths422Error: Partial<DownloadFilePaths422Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { downloadFilePaths422Error.detail = n.getStringValue(); },
        "errors": n => { downloadFilePaths422Error.errors = n.getObjectValue<DownloadFilePaths422Error_errors>(createDownloadFilePaths422Error_errorsFromDiscriminatorValue); },
        "instance": n => { downloadFilePaths422Error.instance = n.getStringValue(); },
        "status": n => { downloadFilePaths422Error.status = n.getNumberValue(); },
        "title": n => { downloadFilePaths422Error.title = n.getStringValue(); },
        "type": n => { downloadFilePaths422Error.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePaths422Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePaths422Error_errors(downloadFilePaths422Error_errors: Partial<DownloadFilePaths422Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePaths429Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePaths429Error(downloadFilePaths429Error: Partial<DownloadFilePaths429Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { downloadFilePaths429Error.detail = n.getStringValue(); },
        "errors": n => { downloadFilePaths429Error.errors = n.getObjectValue<DownloadFilePaths429Error_errors>(createDownloadFilePaths429Error_errorsFromDiscriminatorValue); },
        "instance": n => { downloadFilePaths429Error.instance = n.getStringValue(); },
        "status": n => { downloadFilePaths429Error.status = n.getNumberValue(); },
        "title": n => { downloadFilePaths429Error.title = n.getStringValue(); },
        "type": n => { downloadFilePaths429Error.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePaths429Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePaths429Error_errors(downloadFilePaths429Error_errors: Partial<DownloadFilePaths429Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePaths500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePaths500Error(downloadFilePaths500Error: Partial<DownloadFilePaths500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { downloadFilePaths500Error.detail = n.getStringValue(); },
        "errors": n => { downloadFilePaths500Error.errors = n.getObjectValue<DownloadFilePaths500Error_errors>(createDownloadFilePaths500Error_errorsFromDiscriminatorValue); },
        "instance": n => { downloadFilePaths500Error.instance = n.getStringValue(); },
        "status": n => { downloadFilePaths500Error.status = n.getNumberValue(); },
        "title": n => { downloadFilePaths500Error.title = n.getStringValue(); },
        "type": n => { downloadFilePaths500Error.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePaths500Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePaths500Error_errors(downloadFilePaths500Error_errors: Partial<DownloadFilePaths500Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePathsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePathsPostRequestBody(downloadFilePathsPostRequestBody: Partial<DownloadFilePathsPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "paths": n => { downloadFilePathsPostRequestBody.paths = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePathsPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePathsPostResponse(downloadFilePathsPostResponse: Partial<DownloadFilePathsPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "etag": n => { downloadFilePathsPostResponse.etag = n.getStringValue(); },
        "files": n => { downloadFilePathsPostResponse.files = n.getCollectionOfObjectValues<DownloadFilePathsPostResponse_files>(createDownloadFilePathsPostResponse_filesFromDiscriminatorValue); },
        "generatedAt": n => { downloadFilePathsPostResponse.generatedAt = n.getStringValue(); },
        "version": n => { downloadFilePathsPostResponse.version = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilePathsPostResponse_files The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilePathsPostResponse_files(downloadFilePathsPostResponse_files: Partial<DownloadFilePathsPostResponse_files> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "path": n => { downloadFilePathsPostResponse_files.path = n.getStringValue(); },
        "url": n => { downloadFilePathsPostResponse_files.url = n.getStringValue(); },
    }
}
export interface DownloadFilePaths400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: DownloadFilePaths400Error_errors | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface DownloadFilePaths400Error_errors extends AdditionalDataHolder, Parsable {
}
export interface DownloadFilePaths422Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: DownloadFilePaths422Error_errors | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface DownloadFilePaths422Error_errors extends AdditionalDataHolder, Parsable {
}
export interface DownloadFilePaths429Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: DownloadFilePaths429Error_errors | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface DownloadFilePaths429Error_errors extends AdditionalDataHolder, Parsable {
}
export interface DownloadFilePaths500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: DownloadFilePaths500Error_errors | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface DownloadFilePaths500Error_errors extends AdditionalDataHolder, Parsable {
}
export interface DownloadFilePathsPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The paths property
     */
    paths?: string[] | null;
}
export interface DownloadFilePathsPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * The etag property
     */
    etag?: string | null;
    /**
     * The files property
     */
    files?: DownloadFilePathsPostResponse_files[] | null;
    /**
     * The generatedAt property
     */
    generatedAt?: string | null;
    /**
     * The version property
     */
    version?: number | null;
}
export interface DownloadFilePathsPostResponse_files extends AdditionalDataHolder, Parsable {
    /**
     * The path property
     */
    path?: string | null;
    /**
     * The url property
     */
    url?: string | null;
}
/**
 * Builds and executes requests for operations under /download-file-paths
 */
export interface DownloadFilePathsRequestBuilder extends BaseRequestBuilder<DownloadFilePathsRequestBuilder> {
    /**
     * 指定したリポジトリから複数ファイルの RAW URL を生成し、JSON で返却するエンドポイントです。用途: UI からの一括ダウンロードや外部連携。リクエスト:- JSON Body { paths: string[] } を必須とし、空文字・重複・不正パスを検証します。制限:- 件数上限: 300。- 単一ファイル上限: 104857600 bytes。合計上限: 1073741824 bytes。レート制限:- Token Bucket を使用します。X-RateLimit-* ヘッダを返却し、超過時は 429 を返します。キャッシュ:- If-None-Match を評価し、ETag が一致する場合は 304 を返します。エラー応答:- application/problem+json を返します。type は validation / unprocessable / rate-limit / internal を使用します。
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DownloadFilePathsPostResponse>}
     * @throws {DownloadFilePaths400Error} error when the service returns a 400 status code
     * @throws {DownloadFilePaths422Error} error when the service returns a 422 status code
     * @throws {DownloadFilePaths429Error} error when the service returns a 429 status code
     * @throws {DownloadFilePaths500Error} error when the service returns a 500 status code
     */
     post(body: DownloadFilePathsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DownloadFilePathsPostResponse | undefined>;
    /**
     * 指定したリポジトリから複数ファイルの RAW URL を生成し、JSON で返却するエンドポイントです。用途: UI からの一括ダウンロードや外部連携。リクエスト:- JSON Body { paths: string[] } を必須とし、空文字・重複・不正パスを検証します。制限:- 件数上限: 300。- 単一ファイル上限: 104857600 bytes。合計上限: 1073741824 bytes。レート制限:- Token Bucket を使用します。X-RateLimit-* ヘッダを返却し、超過時は 429 を返します。キャッシュ:- If-None-Match を評価し、ETag が一致する場合は 304 を返します。エラー応答:- application/problem+json を返します。type は validation / unprocessable / rate-limit / internal を使用します。
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: DownloadFilePathsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param DownloadFilePaths400Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePaths400Error(writer: SerializationWriter, downloadFilePaths400Error: Partial<DownloadFilePaths400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePaths400Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", downloadFilePaths400Error.detail);
    writer.writeObjectValue<DownloadFilePaths400Error_errors>("errors", downloadFilePaths400Error.errors, serializeDownloadFilePaths400Error_errors);
    writer.writeStringValue("instance", downloadFilePaths400Error.instance);
    writer.writeNumberValue("status", downloadFilePaths400Error.status);
    writer.writeStringValue("title", downloadFilePaths400Error.title);
    writer.writeStringValue("type", downloadFilePaths400Error.type);
    writer.writeAdditionalData(downloadFilePaths400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePaths400Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePaths400Error_errors(writer: SerializationWriter, downloadFilePaths400Error_errors: Partial<DownloadFilePaths400Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePaths400Error_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(downloadFilePaths400Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePaths422Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePaths422Error(writer: SerializationWriter, downloadFilePaths422Error: Partial<DownloadFilePaths422Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePaths422Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", downloadFilePaths422Error.detail);
    writer.writeObjectValue<DownloadFilePaths422Error_errors>("errors", downloadFilePaths422Error.errors, serializeDownloadFilePaths422Error_errors);
    writer.writeStringValue("instance", downloadFilePaths422Error.instance);
    writer.writeNumberValue("status", downloadFilePaths422Error.status);
    writer.writeStringValue("title", downloadFilePaths422Error.title);
    writer.writeStringValue("type", downloadFilePaths422Error.type);
    writer.writeAdditionalData(downloadFilePaths422Error.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePaths422Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePaths422Error_errors(writer: SerializationWriter, downloadFilePaths422Error_errors: Partial<DownloadFilePaths422Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePaths422Error_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(downloadFilePaths422Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePaths429Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePaths429Error(writer: SerializationWriter, downloadFilePaths429Error: Partial<DownloadFilePaths429Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePaths429Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", downloadFilePaths429Error.detail);
    writer.writeObjectValue<DownloadFilePaths429Error_errors>("errors", downloadFilePaths429Error.errors, serializeDownloadFilePaths429Error_errors);
    writer.writeStringValue("instance", downloadFilePaths429Error.instance);
    writer.writeNumberValue("status", downloadFilePaths429Error.status);
    writer.writeStringValue("title", downloadFilePaths429Error.title);
    writer.writeStringValue("type", downloadFilePaths429Error.type);
    writer.writeAdditionalData(downloadFilePaths429Error.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePaths429Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePaths429Error_errors(writer: SerializationWriter, downloadFilePaths429Error_errors: Partial<DownloadFilePaths429Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePaths429Error_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(downloadFilePaths429Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePaths500Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePaths500Error(writer: SerializationWriter, downloadFilePaths500Error: Partial<DownloadFilePaths500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePaths500Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", downloadFilePaths500Error.detail);
    writer.writeObjectValue<DownloadFilePaths500Error_errors>("errors", downloadFilePaths500Error.errors, serializeDownloadFilePaths500Error_errors);
    writer.writeStringValue("instance", downloadFilePaths500Error.instance);
    writer.writeNumberValue("status", downloadFilePaths500Error.status);
    writer.writeStringValue("title", downloadFilePaths500Error.title);
    writer.writeStringValue("type", downloadFilePaths500Error.type);
    writer.writeAdditionalData(downloadFilePaths500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePaths500Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePaths500Error_errors(writer: SerializationWriter, downloadFilePaths500Error_errors: Partial<DownloadFilePaths500Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePaths500Error_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(downloadFilePaths500Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePathsPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePathsPostRequestBody(writer: SerializationWriter, downloadFilePathsPostRequestBody: Partial<DownloadFilePathsPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePathsPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("paths", downloadFilePathsPostRequestBody.paths);
    writer.writeAdditionalData(downloadFilePathsPostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePathsPostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePathsPostResponse(writer: SerializationWriter, downloadFilePathsPostResponse: Partial<DownloadFilePathsPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePathsPostResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("etag", downloadFilePathsPostResponse.etag);
    writer.writeCollectionOfObjectValues<DownloadFilePathsPostResponse_files>("files", downloadFilePathsPostResponse.files, serializeDownloadFilePathsPostResponse_files);
    writer.writeStringValue("generatedAt", downloadFilePathsPostResponse.generatedAt);
    writer.writeNumberValue("version", downloadFilePathsPostResponse.version);
    writer.writeAdditionalData(downloadFilePathsPostResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilePathsPostResponse_files The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilePathsPostResponse_files(writer: SerializationWriter, downloadFilePathsPostResponse_files: Partial<DownloadFilePathsPostResponse_files> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilePathsPostResponse_files || isSerializingDerivedType) { return; }
    writer.writeStringValue("path", downloadFilePathsPostResponse_files.path);
    writer.writeStringValue("url", downloadFilePathsPostResponse_files.url);
    writer.writeAdditionalData(downloadFilePathsPostResponse_files.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const DownloadFilePathsRequestBuilderUriTemplate = "{+baseurl}/download-file-paths";
/**
 * Metadata for all the requests in the request builder.
 */
export const DownloadFilePathsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DownloadFilePathsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createDownloadFilePaths400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createDownloadFilePaths422ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createDownloadFilePaths429ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createDownloadFilePaths500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDownloadFilePathsPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDownloadFilePathsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
