/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

export interface Create400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface Create403Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface Create404Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface Create422Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface Create500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Create400Error}
 */
// @ts-ignore
export function createCreate400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreate400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Create403Error}
 */
// @ts-ignore
export function createCreate403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreate403Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Create404Error}
 */
// @ts-ignore
export function createCreate404ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreate404Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Create422Error}
 */
// @ts-ignore
export function createCreate422ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreate422Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Create500Error}
 */
// @ts-ignore
export function createCreate500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreate500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePostRequestBody}
 */
// @ts-ignore
export function createCreatePostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePostResponse_data}
 */
// @ts-ignore
export function createCreatePostResponse_dataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePostResponse_data;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePostResponse}
 */
// @ts-ignore
export function createCreatePostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePostResponse;
}
export interface CreatePostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The assignees property
     */
    assignees?: string[] | null;
    /**
     * The body property
     */
    body?: string | null;
    /**
     * The labels property
     */
    labels?: string[] | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface CreatePostResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: CreatePostResponse_data[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreatePostResponse_data extends AdditionalDataHolder, Parsable {
    /**
     * The issueNumber property
     */
    issueNumber?: number | null;
    /**
     * The issueUrl property
     */
    issueUrl?: string | null;
}
/**
 * Builds and executes requests for operations under /issue/create
 */
export interface CreateRequestBuilder extends BaseRequestBuilder<CreateRequestBuilder> {
    /**
     * 指定のリポジトリに Issue を作成します。リクエスト:- title: Issue のタイトル（必須）- body: Issue の本文（任意）- labels: 適用するラベル配列（任意）- assignees: アサインするユーザー配列（任意）応答:- 成功時は issueNumber と issueUrl を含む配列を返します。エラー:- 400: リクエスト不正- 403: 権限不足- 404: リポジトリが見つからない- 422: 処理不能（内容不整合など）- 500: サーバーエラー
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreatePostResponse>}
     * @throws {Create400Error} error when the service returns a 400 status code
     * @throws {Create403Error} error when the service returns a 403 status code
     * @throws {Create404Error} error when the service returns a 404 status code
     * @throws {Create422Error} error when the service returns a 422 status code
     * @throws {Create500Error} error when the service returns a 500 status code
     */
     post(body: CreatePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreatePostResponse | undefined>;
    /**
     * 指定のリポジトリに Issue を作成します。リクエスト:- title: Issue のタイトル（必須）- body: Issue の本文（任意）- labels: 適用するラベル配列（任意）- assignees: アサインするユーザー配列（任意）応答:- 成功時は issueNumber と issueUrl を含む配列を返します。エラー:- 400: リクエスト不正- 403: 権限不足- 404: リポジトリが見つからない- 422: 処理不能（内容不整合など）- 500: サーバーエラー
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The deserialization information for the current model
 * @param Create400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreate400Error(create400Error: Partial<Create400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { create400Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { create400Error.messageEscaped = n.getStringValue(); },
        "success": n => { create400Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Create403Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreate403Error(create403Error: Partial<Create403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { create403Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { create403Error.messageEscaped = n.getStringValue(); },
        "success": n => { create403Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Create404Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreate404Error(create404Error: Partial<Create404Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { create404Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { create404Error.messageEscaped = n.getStringValue(); },
        "success": n => { create404Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Create422Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreate422Error(create422Error: Partial<Create422Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { create422Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { create422Error.messageEscaped = n.getStringValue(); },
        "success": n => { create422Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Create500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreate500Error(create500Error: Partial<Create500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { create500Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { create500Error.messageEscaped = n.getStringValue(); },
        "success": n => { create500Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePostRequestBody(createPostRequestBody: Partial<CreatePostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "assignees": n => { createPostRequestBody.assignees = n.getCollectionOfPrimitiveValues<string>(); },
        "body": n => { createPostRequestBody.body = n.getStringValue(); },
        "labels": n => { createPostRequestBody.labels = n.getCollectionOfPrimitiveValues<string>(); },
        "title": n => { createPostRequestBody.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePostResponse(createPostResponse: Partial<CreatePostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createPostResponse.data = n.getCollectionOfObjectValues<CreatePostResponse_data>(createCreatePostResponse_dataFromDiscriminatorValue); },
        "message": n => { createPostResponse.message = n.getStringValue(); },
        "success": n => { createPostResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePostResponse_data The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePostResponse_data(createPostResponse_data: Partial<CreatePostResponse_data> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "issueNumber": n => { createPostResponse_data.issueNumber = n.getNumberValue(); },
        "issueUrl": n => { createPostResponse_data.issueUrl = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param Create400Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreate400Error(writer: SerializationWriter, create400Error: Partial<Create400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!create400Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", create400Error.data);
    writer.writeStringValue("message", create400Error.messageEscaped);
    writer.writeBooleanValue("success", create400Error.success);
    writer.writeAdditionalData(create400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param Create403Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreate403Error(writer: SerializationWriter, create403Error: Partial<Create403Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!create403Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", create403Error.data);
    writer.writeStringValue("message", create403Error.messageEscaped);
    writer.writeBooleanValue("success", create403Error.success);
    writer.writeAdditionalData(create403Error.additionalData);
}
/**
 * Serializes information the current object
 * @param Create404Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreate404Error(writer: SerializationWriter, create404Error: Partial<Create404Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!create404Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", create404Error.data);
    writer.writeStringValue("message", create404Error.messageEscaped);
    writer.writeBooleanValue("success", create404Error.success);
    writer.writeAdditionalData(create404Error.additionalData);
}
/**
 * Serializes information the current object
 * @param Create422Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreate422Error(writer: SerializationWriter, create422Error: Partial<Create422Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!create422Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", create422Error.data);
    writer.writeStringValue("message", create422Error.messageEscaped);
    writer.writeBooleanValue("success", create422Error.success);
    writer.writeAdditionalData(create422Error.additionalData);
}
/**
 * Serializes information the current object
 * @param Create500Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreate500Error(writer: SerializationWriter, create500Error: Partial<Create500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!create500Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", create500Error.data);
    writer.writeStringValue("message", create500Error.messageEscaped);
    writer.writeBooleanValue("success", create500Error.success);
    writer.writeAdditionalData(create500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePostRequestBody(writer: SerializationWriter, createPostRequestBody: Partial<CreatePostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("assignees", createPostRequestBody.assignees);
    writer.writeStringValue("body", createPostRequestBody.body);
    writer.writeCollectionOfPrimitiveValues<string>("labels", createPostRequestBody.labels);
    writer.writeStringValue("title", createPostRequestBody.title);
    writer.writeAdditionalData(createPostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePostResponse(writer: SerializationWriter, createPostResponse: Partial<CreatePostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPostResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<CreatePostResponse_data>("data", createPostResponse.data, serializeCreatePostResponse_data);
    writer.writeStringValue("message", createPostResponse.message);
    writer.writeBooleanValue("success", createPostResponse.success);
    writer.writeAdditionalData(createPostResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePostResponse_data The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePostResponse_data(writer: SerializationWriter, createPostResponse_data: Partial<CreatePostResponse_data> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPostResponse_data || isSerializingDerivedType) { return; }
    writer.writeNumberValue("issueNumber", createPostResponse_data.issueNumber);
    writer.writeStringValue("issueUrl", createPostResponse_data.issueUrl);
    writer.writeAdditionalData(createPostResponse_data.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const CreateRequestBuilderUriTemplate = "{+baseurl}/issue/create";
/**
 * Metadata for all the requests in the request builder.
 */
export const CreateRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CreateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createCreate400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createCreate403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createCreate404ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createCreate422ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createCreate500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreatePostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
