/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type UpsertRequestBuilder, UpsertRequestBuilderRequestsMetadata } from './upsert/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /tree-metadata
 */
export interface TreeMetadataRequestBuilder extends BaseRequestBuilder<TreeMetadataRequestBuilder> {
    /**
     * The upsert property
     */
    get upsert(): UpsertRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TreeMetadataRequestBuilderUriTemplate = "{+baseurl}/tree-metadata";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TreeMetadataRequestBuilderNavigationMetadata: Record<Exclude<keyof TreeMetadataRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    upsert: {
        requestsMetadata: UpsertRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
