/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Upsert400Error}
 */
// @ts-ignore
export function createUpsert400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpsert400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Upsert401Error}
 */
// @ts-ignore
export function createUpsert401ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpsert401Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Upsert403Error}
 */
// @ts-ignore
export function createUpsert403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpsert403Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Upsert404Error}
 */
// @ts-ignore
export function createUpsert404ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpsert404Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Upsert422Error}
 */
// @ts-ignore
export function createUpsert422ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpsert422Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Upsert500Error}
 */
// @ts-ignore
export function createUpsert500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpsert500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Upsert}
 */
// @ts-ignore
export function createUpsertFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpsert;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpsertPostResponse}
 */
// @ts-ignore
export function createUpsertPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpsertPostResponse;
}
/**
 * The deserialization information for the current model
 * @param Upsert The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpsert(upsert: Partial<Upsert> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "path": n => { upsert.path = n.getStringValue(); },
        "updatedAt": n => { upsert.updatedAt = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Upsert400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpsert400Error(upsert400Error: Partial<Upsert400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { upsert400Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { upsert400Error.messageEscaped = n.getStringValue(); },
        "success": n => { upsert400Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Upsert401Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpsert401Error(upsert401Error: Partial<Upsert401Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { upsert401Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { upsert401Error.messageEscaped = n.getStringValue(); },
        "success": n => { upsert401Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Upsert403Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpsert403Error(upsert403Error: Partial<Upsert403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { upsert403Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { upsert403Error.messageEscaped = n.getStringValue(); },
        "success": n => { upsert403Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Upsert404Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpsert404Error(upsert404Error: Partial<Upsert404Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { upsert404Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { upsert404Error.messageEscaped = n.getStringValue(); },
        "success": n => { upsert404Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Upsert422Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpsert422Error(upsert422Error: Partial<Upsert422Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { upsert422Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { upsert422Error.messageEscaped = n.getStringValue(); },
        "success": n => { upsert422Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Upsert500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpsert500Error(upsert500Error: Partial<Upsert500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { upsert500Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { upsert500Error.messageEscaped = n.getStringValue(); },
        "success": n => { upsert500Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpsertPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpsertPostResponse(upsertPostResponse: Partial<UpsertPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { upsertPostResponse.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { upsertPostResponse.message = n.getStringValue(); },
        "success": n => { upsertPostResponse.success = n.getBooleanValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Upsert The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpsert(writer: SerializationWriter, upsert: Partial<Upsert> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!upsert || isSerializingDerivedType) { return; }
    writer.writeStringValue("path", upsert.path);
    writer.writeNumberValue("updatedAt", upsert.updatedAt);
    writer.writeAdditionalData(upsert.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Upsert400Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpsert400Error(writer: SerializationWriter, upsert400Error: Partial<Upsert400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!upsert400Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", upsert400Error.data);
    writer.writeStringValue("message", upsert400Error.messageEscaped);
    writer.writeBooleanValue("success", upsert400Error.success);
    writer.writeAdditionalData(upsert400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Upsert401Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpsert401Error(writer: SerializationWriter, upsert401Error: Partial<Upsert401Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!upsert401Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", upsert401Error.data);
    writer.writeStringValue("message", upsert401Error.messageEscaped);
    writer.writeBooleanValue("success", upsert401Error.success);
    writer.writeAdditionalData(upsert401Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Upsert403Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpsert403Error(writer: SerializationWriter, upsert403Error: Partial<Upsert403Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!upsert403Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", upsert403Error.data);
    writer.writeStringValue("message", upsert403Error.messageEscaped);
    writer.writeBooleanValue("success", upsert403Error.success);
    writer.writeAdditionalData(upsert403Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Upsert404Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpsert404Error(writer: SerializationWriter, upsert404Error: Partial<Upsert404Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!upsert404Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", upsert404Error.data);
    writer.writeStringValue("message", upsert404Error.messageEscaped);
    writer.writeBooleanValue("success", upsert404Error.success);
    writer.writeAdditionalData(upsert404Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Upsert422Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpsert422Error(writer: SerializationWriter, upsert422Error: Partial<Upsert422Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!upsert422Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", upsert422Error.data);
    writer.writeStringValue("message", upsert422Error.messageEscaped);
    writer.writeBooleanValue("success", upsert422Error.success);
    writer.writeAdditionalData(upsert422Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Upsert500Error The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpsert500Error(writer: SerializationWriter, upsert500Error: Partial<Upsert500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!upsert500Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", upsert500Error.data);
    writer.writeStringValue("message", upsert500Error.messageEscaped);
    writer.writeBooleanValue("success", upsert500Error.success);
    writer.writeAdditionalData(upsert500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpsertPostResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpsertPostResponse(writer: SerializationWriter, upsertPostResponse: Partial<UpsertPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!upsertPostResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", upsertPostResponse.data);
    writer.writeStringValue("message", upsertPostResponse.message);
    writer.writeBooleanValue("success", upsertPostResponse.success);
    writer.writeAdditionalData(upsertPostResponse.additionalData);
}
export interface Upsert extends AdditionalDataHolder, Parsable {
    /**
     * The path property
     */
    path?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: number | null;
}
export interface Upsert400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface Upsert401Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface Upsert403Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface Upsert404Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface Upsert422Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface Upsert500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface UpsertPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
/**
 * Builds and executes requests for operations under /tree-metadata/upsert
 */
export interface UpsertRequestBuilder extends BaseRequestBuilder<UpsertRequestBuilder> {
    /**
     * GitHub の ファイルの作成・更新日を更新します。
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UpsertPostResponse>}
     * @throws {Upsert400Error} error when the service returns a 400 status code
     * @throws {Upsert401Error} error when the service returns a 401 status code
     * @throws {Upsert403Error} error when the service returns a 403 status code
     * @throws {Upsert404Error} error when the service returns a 404 status code
     * @throws {Upsert422Error} error when the service returns a 422 status code
     * @throws {Upsert500Error} error when the service returns a 500 status code
     */
     post(body: Upsert[], requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UpsertPostResponse | undefined>;
    /**
     * GitHub の ファイルの作成・更新日を更新します。
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: Upsert[], requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UpsertRequestBuilderUriTemplate = "{+baseurl}/tree-metadata/upsert";
/**
 * Metadata for all the requests in the request builder.
 */
export const UpsertRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: UpsertRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createUpsert400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createUpsert401ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createUpsert403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createUpsert404ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createUpsert422ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createUpsert500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUpsertPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpsert,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
