/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateIssue400Error}
 */
// @ts-ignore
export function createCreateIssue400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateIssue400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateIssue403Error}
 */
// @ts-ignore
export function createCreateIssue403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateIssue403Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateIssue422Error}
 */
// @ts-ignore
export function createCreateIssue422ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateIssue422Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateIssue500Error}
 */
// @ts-ignore
export function createCreateIssue500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateIssue500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateIssuePostRequestBody}
 */
// @ts-ignore
export function createCreateIssuePostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateIssuePostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateIssuePostResponse_data}
 */
// @ts-ignore
export function createCreateIssuePostResponse_dataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateIssuePostResponse_data;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateIssuePostResponse}
 */
// @ts-ignore
export function createCreateIssuePostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateIssuePostResponse;
}
export interface CreateIssue400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreateIssue403Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreateIssue422Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreateIssue500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreateIssuePostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The assignees property
     */
    assignees?: string[] | null;
    /**
     * The body property
     */
    body?: string | null;
    /**
     * The labels property
     */
    labels?: string[] | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface CreateIssuePostResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: CreateIssuePostResponse_data[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreateIssuePostResponse_data extends AdditionalDataHolder, Parsable {
    /**
     * The issueNumber property
     */
    issueNumber?: number | null;
    /**
     * The issueUrl property
     */
    issueUrl?: string | null;
}
/**
 * Builds and executes requests for operations under /create-issue
 */
export interface CreateIssueRequestBuilder extends BaseRequestBuilder<CreateIssueRequestBuilder> {
    /**
     * 指定のリポジトリに Issue を作成します。リクエスト:- title: Issue のタイトル（必須）- body: Issue の本文（任意）- labels: 適用するラベル配列（任意）- assignees: アサインするユーザー配列（任意）応答:- 成功時は issueNumber と issueUrl を含む配列を返します。エラー:- 400: リクエスト不正- 403: 権限不足- 422: 処理不能（内容不整合など）- 500: サーバーエラー
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateIssuePostResponse>}
     * @throws {CreateIssue400Error} error when the service returns a 400 status code
     * @throws {CreateIssue403Error} error when the service returns a 403 status code
     * @throws {CreateIssue422Error} error when the service returns a 422 status code
     * @throws {CreateIssue500Error} error when the service returns a 500 status code
     */
     post(body: CreateIssuePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreateIssuePostResponse | undefined>;
    /**
     * 指定のリポジトリに Issue を作成します。リクエスト:- title: Issue のタイトル（必須）- body: Issue の本文（任意）- labels: 適用するラベル配列（任意）- assignees: アサインするユーザー配列（任意）応答:- 成功時は issueNumber と issueUrl を含む配列を返します。エラー:- 400: リクエスト不正- 403: 権限不足- 422: 処理不能（内容不整合など）- 500: サーバーエラー
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateIssuePostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The deserialization information for the current model
 * @param CreateIssue400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateIssue400Error(createIssue400Error: Partial<CreateIssue400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createIssue400Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { createIssue400Error.messageEscaped = n.getStringValue(); },
        "success": n => { createIssue400Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateIssue403Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateIssue403Error(createIssue403Error: Partial<CreateIssue403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createIssue403Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { createIssue403Error.messageEscaped = n.getStringValue(); },
        "success": n => { createIssue403Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateIssue422Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateIssue422Error(createIssue422Error: Partial<CreateIssue422Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createIssue422Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { createIssue422Error.messageEscaped = n.getStringValue(); },
        "success": n => { createIssue422Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateIssue500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateIssue500Error(createIssue500Error: Partial<CreateIssue500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createIssue500Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { createIssue500Error.messageEscaped = n.getStringValue(); },
        "success": n => { createIssue500Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateIssuePostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateIssuePostRequestBody(createIssuePostRequestBody: Partial<CreateIssuePostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "assignees": n => { createIssuePostRequestBody.assignees = n.getCollectionOfPrimitiveValues<string>(); },
        "body": n => { createIssuePostRequestBody.body = n.getStringValue(); },
        "labels": n => { createIssuePostRequestBody.labels = n.getCollectionOfPrimitiveValues<string>(); },
        "title": n => { createIssuePostRequestBody.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateIssuePostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateIssuePostResponse(createIssuePostResponse: Partial<CreateIssuePostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createIssuePostResponse.data = n.getCollectionOfObjectValues<CreateIssuePostResponse_data>(createCreateIssuePostResponse_dataFromDiscriminatorValue); },
        "message": n => { createIssuePostResponse.message = n.getStringValue(); },
        "success": n => { createIssuePostResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateIssuePostResponse_data The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateIssuePostResponse_data(createIssuePostResponse_data: Partial<CreateIssuePostResponse_data> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "issueNumber": n => { createIssuePostResponse_data.issueNumber = n.getNumberValue(); },
        "issueUrl": n => { createIssuePostResponse_data.issueUrl = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param CreateIssue400Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateIssue400Error(writer: SerializationWriter, createIssue400Error: Partial<CreateIssue400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createIssue400Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", createIssue400Error.data);
    writer.writeStringValue("message", createIssue400Error.messageEscaped);
    writer.writeBooleanValue("success", createIssue400Error.success);
    writer.writeAdditionalData(createIssue400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateIssue403Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateIssue403Error(writer: SerializationWriter, createIssue403Error: Partial<CreateIssue403Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createIssue403Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", createIssue403Error.data);
    writer.writeStringValue("message", createIssue403Error.messageEscaped);
    writer.writeBooleanValue("success", createIssue403Error.success);
    writer.writeAdditionalData(createIssue403Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateIssue422Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateIssue422Error(writer: SerializationWriter, createIssue422Error: Partial<CreateIssue422Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createIssue422Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", createIssue422Error.data);
    writer.writeStringValue("message", createIssue422Error.messageEscaped);
    writer.writeBooleanValue("success", createIssue422Error.success);
    writer.writeAdditionalData(createIssue422Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateIssue500Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateIssue500Error(writer: SerializationWriter, createIssue500Error: Partial<CreateIssue500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createIssue500Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", createIssue500Error.data);
    writer.writeStringValue("message", createIssue500Error.messageEscaped);
    writer.writeBooleanValue("success", createIssue500Error.success);
    writer.writeAdditionalData(createIssue500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateIssuePostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateIssuePostRequestBody(writer: SerializationWriter, createIssuePostRequestBody: Partial<CreateIssuePostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createIssuePostRequestBody || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("assignees", createIssuePostRequestBody.assignees);
    writer.writeStringValue("body", createIssuePostRequestBody.body);
    writer.writeCollectionOfPrimitiveValues<string>("labels", createIssuePostRequestBody.labels);
    writer.writeStringValue("title", createIssuePostRequestBody.title);
    writer.writeAdditionalData(createIssuePostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateIssuePostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateIssuePostResponse(writer: SerializationWriter, createIssuePostResponse: Partial<CreateIssuePostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createIssuePostResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<CreateIssuePostResponse_data>("data", createIssuePostResponse.data, serializeCreateIssuePostResponse_data);
    writer.writeStringValue("message", createIssuePostResponse.message);
    writer.writeBooleanValue("success", createIssuePostResponse.success);
    writer.writeAdditionalData(createIssuePostResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateIssuePostResponse_data The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateIssuePostResponse_data(writer: SerializationWriter, createIssuePostResponse_data: Partial<CreateIssuePostResponse_data> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createIssuePostResponse_data || isSerializingDerivedType) { return; }
    writer.writeNumberValue("issueNumber", createIssuePostResponse_data.issueNumber);
    writer.writeStringValue("issueUrl", createIssuePostResponse_data.issueUrl);
    writer.writeAdditionalData(createIssuePostResponse_data.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const CreateIssueRequestBuilderUriTemplate = "{+baseurl}/create-issue";
/**
 * Metadata for all the requests in the request builder.
 */
export const CreateIssueRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CreateIssueRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createCreateIssue400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createCreateIssue403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createCreateIssue422ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createCreateIssue500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreateIssuePostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateIssuePostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
