/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFiles400Error_errors}
 */
// @ts-ignore
export function createDownloadFiles400Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFiles400Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFiles400Error}
 */
// @ts-ignore
export function createDownloadFiles400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFiles400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFiles422Error_errors}
 */
// @ts-ignore
export function createDownloadFiles422Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFiles422Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFiles422Error}
 */
// @ts-ignore
export function createDownloadFiles422ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFiles422Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFiles429Error_errors}
 */
// @ts-ignore
export function createDownloadFiles429Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFiles429Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFiles429Error}
 */
// @ts-ignore
export function createDownloadFiles429ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFiles429Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFiles500Error_errors}
 */
// @ts-ignore
export function createDownloadFiles500Error_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFiles500Error_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFiles500Error}
 */
// @ts-ignore
export function createDownloadFiles500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFiles500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DownloadFilesPostRequestBody}
 */
// @ts-ignore
export function createDownloadFilesPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDownloadFilesPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param DownloadFiles400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFiles400Error(downloadFiles400Error: Partial<DownloadFiles400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { downloadFiles400Error.detail = n.getStringValue(); },
        "errors": n => { downloadFiles400Error.errors = n.getObjectValue<DownloadFiles400Error_errors>(createDownloadFiles400Error_errorsFromDiscriminatorValue); },
        "instance": n => { downloadFiles400Error.instance = n.getStringValue(); },
        "status": n => { downloadFiles400Error.status = n.getNumberValue(); },
        "title": n => { downloadFiles400Error.title = n.getStringValue(); },
        "type": n => { downloadFiles400Error.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFiles400Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFiles400Error_errors(downloadFiles400Error_errors: Partial<DownloadFiles400Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFiles422Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFiles422Error(downloadFiles422Error: Partial<DownloadFiles422Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { downloadFiles422Error.detail = n.getStringValue(); },
        "errors": n => { downloadFiles422Error.errors = n.getObjectValue<DownloadFiles422Error_errors>(createDownloadFiles422Error_errorsFromDiscriminatorValue); },
        "instance": n => { downloadFiles422Error.instance = n.getStringValue(); },
        "status": n => { downloadFiles422Error.status = n.getNumberValue(); },
        "title": n => { downloadFiles422Error.title = n.getStringValue(); },
        "type": n => { downloadFiles422Error.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFiles422Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFiles422Error_errors(downloadFiles422Error_errors: Partial<DownloadFiles422Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFiles429Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFiles429Error(downloadFiles429Error: Partial<DownloadFiles429Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { downloadFiles429Error.detail = n.getStringValue(); },
        "errors": n => { downloadFiles429Error.errors = n.getObjectValue<DownloadFiles429Error_errors>(createDownloadFiles429Error_errorsFromDiscriminatorValue); },
        "instance": n => { downloadFiles429Error.instance = n.getStringValue(); },
        "status": n => { downloadFiles429Error.status = n.getNumberValue(); },
        "title": n => { downloadFiles429Error.title = n.getStringValue(); },
        "type": n => { downloadFiles429Error.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFiles429Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFiles429Error_errors(downloadFiles429Error_errors: Partial<DownloadFiles429Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFiles500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFiles500Error(downloadFiles500Error: Partial<DownloadFiles500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { downloadFiles500Error.detail = n.getStringValue(); },
        "errors": n => { downloadFiles500Error.errors = n.getObjectValue<DownloadFiles500Error_errors>(createDownloadFiles500Error_errorsFromDiscriminatorValue); },
        "instance": n => { downloadFiles500Error.instance = n.getStringValue(); },
        "status": n => { downloadFiles500Error.status = n.getNumberValue(); },
        "title": n => { downloadFiles500Error.title = n.getStringValue(); },
        "type": n => { downloadFiles500Error.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFiles500Error_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFiles500Error_errors(downloadFiles500Error_errors: Partial<DownloadFiles500Error_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DownloadFilesPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDownloadFilesPostRequestBody(downloadFilesPostRequestBody: Partial<DownloadFilesPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "paths": n => { downloadFilesPostRequestBody.paths = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
export interface DownloadFiles400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: DownloadFiles400Error_errors | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface DownloadFiles400Error_errors extends AdditionalDataHolder, Parsable {
}
export interface DownloadFiles422Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: DownloadFiles422Error_errors | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface DownloadFiles422Error_errors extends AdditionalDataHolder, Parsable {
}
export interface DownloadFiles429Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: DownloadFiles429Error_errors | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface DownloadFiles429Error_errors extends AdditionalDataHolder, Parsable {
}
export interface DownloadFiles500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: DownloadFiles500Error_errors | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface DownloadFiles500Error_errors extends AdditionalDataHolder, Parsable {
}
export interface DownloadFilesPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The paths property
     */
    paths?: string[] | null;
}
/**
 * Builds and executes requests for operations under /download-files
 */
export interface DownloadFilesRequestBuilder extends BaseRequestBuilder<DownloadFilesRequestBuilder> {
    /**
     * 指定したリポジトリから複数のファイルを取得し、ZIP ストリームで返却するエンドポイントです。用途: UI からの一括ダウンロードや外部連携。リクエスト:- JSON Body { paths: string[] } を必須とし、空文字・重複・不正パスを検証します。制限:- 件数上限: 500。- 単一ファイル上限: 104857600 bytes。合計上限: 1073741824 bytes。レート制限:- Token Bucket を使用します。X-RateLimit-* ヘッダを返却し、超過時は 429 を返します。キャッシュ:- If-None-Match を評価し、ETag が一致する場合は 304 を返します。エラー応答:- application/problem+json を返します。type は validation / unprocessable / rate-limit / internal を使用します。
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {DownloadFiles400Error} error when the service returns a 400 status code
     * @throws {DownloadFiles422Error} error when the service returns a 422 status code
     * @throws {DownloadFiles429Error} error when the service returns a 429 status code
     * @throws {DownloadFiles500Error} error when the service returns a 500 status code
     */
     post(body: DownloadFilesPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * 指定したリポジトリから複数のファイルを取得し、ZIP ストリームで返却するエンドポイントです。用途: UI からの一括ダウンロードや外部連携。リクエスト:- JSON Body { paths: string[] } を必須とし、空文字・重複・不正パスを検証します。制限:- 件数上限: 500。- 単一ファイル上限: 104857600 bytes。合計上限: 1073741824 bytes。レート制限:- Token Bucket を使用します。X-RateLimit-* ヘッダを返却し、超過時は 429 を返します。キャッシュ:- If-None-Match を評価し、ETag が一致する場合は 304 を返します。エラー応答:- application/problem+json を返します。type は validation / unprocessable / rate-limit / internal を使用します。
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: DownloadFilesPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param DownloadFiles400Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFiles400Error(writer: SerializationWriter, downloadFiles400Error: Partial<DownloadFiles400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFiles400Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", downloadFiles400Error.detail);
    writer.writeObjectValue<DownloadFiles400Error_errors>("errors", downloadFiles400Error.errors, serializeDownloadFiles400Error_errors);
    writer.writeStringValue("instance", downloadFiles400Error.instance);
    writer.writeNumberValue("status", downloadFiles400Error.status);
    writer.writeStringValue("title", downloadFiles400Error.title);
    writer.writeStringValue("type", downloadFiles400Error.type);
    writer.writeAdditionalData(downloadFiles400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFiles400Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFiles400Error_errors(writer: SerializationWriter, downloadFiles400Error_errors: Partial<DownloadFiles400Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFiles400Error_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(downloadFiles400Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFiles422Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFiles422Error(writer: SerializationWriter, downloadFiles422Error: Partial<DownloadFiles422Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFiles422Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", downloadFiles422Error.detail);
    writer.writeObjectValue<DownloadFiles422Error_errors>("errors", downloadFiles422Error.errors, serializeDownloadFiles422Error_errors);
    writer.writeStringValue("instance", downloadFiles422Error.instance);
    writer.writeNumberValue("status", downloadFiles422Error.status);
    writer.writeStringValue("title", downloadFiles422Error.title);
    writer.writeStringValue("type", downloadFiles422Error.type);
    writer.writeAdditionalData(downloadFiles422Error.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFiles422Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFiles422Error_errors(writer: SerializationWriter, downloadFiles422Error_errors: Partial<DownloadFiles422Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFiles422Error_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(downloadFiles422Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFiles429Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFiles429Error(writer: SerializationWriter, downloadFiles429Error: Partial<DownloadFiles429Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFiles429Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", downloadFiles429Error.detail);
    writer.writeObjectValue<DownloadFiles429Error_errors>("errors", downloadFiles429Error.errors, serializeDownloadFiles429Error_errors);
    writer.writeStringValue("instance", downloadFiles429Error.instance);
    writer.writeNumberValue("status", downloadFiles429Error.status);
    writer.writeStringValue("title", downloadFiles429Error.title);
    writer.writeStringValue("type", downloadFiles429Error.type);
    writer.writeAdditionalData(downloadFiles429Error.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFiles429Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFiles429Error_errors(writer: SerializationWriter, downloadFiles429Error_errors: Partial<DownloadFiles429Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFiles429Error_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(downloadFiles429Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFiles500Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFiles500Error(writer: SerializationWriter, downloadFiles500Error: Partial<DownloadFiles500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFiles500Error || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", downloadFiles500Error.detail);
    writer.writeObjectValue<DownloadFiles500Error_errors>("errors", downloadFiles500Error.errors, serializeDownloadFiles500Error_errors);
    writer.writeStringValue("instance", downloadFiles500Error.instance);
    writer.writeNumberValue("status", downloadFiles500Error.status);
    writer.writeStringValue("title", downloadFiles500Error.title);
    writer.writeStringValue("type", downloadFiles500Error.type);
    writer.writeAdditionalData(downloadFiles500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFiles500Error_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFiles500Error_errors(writer: SerializationWriter, downloadFiles500Error_errors: Partial<DownloadFiles500Error_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFiles500Error_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(downloadFiles500Error_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param DownloadFilesPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDownloadFilesPostRequestBody(writer: SerializationWriter, downloadFilesPostRequestBody: Partial<DownloadFilesPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!downloadFilesPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeCollectionOfPrimitiveValues<string>("paths", downloadFilesPostRequestBody.paths);
    writer.writeAdditionalData(downloadFilesPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const DownloadFilesRequestBuilderUriTemplate = "{+baseurl}/download-files";
/**
 * Metadata for all the requests in the request builder.
 */
export const DownloadFilesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DownloadFilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/zip, application/problem+json",
        errorMappings: {
            400: createDownloadFiles400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createDownloadFiles422ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createDownloadFiles429ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createDownloadFiles500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDownloadFilesPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
