/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CreateRequestBuilderRequestsMetadata, type CreateRequestBuilder } from './create/index.js';
// @ts-ignore
import { ListRequestBuilderRequestsMetadata, type ListRequestBuilder } from './list/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /issue
 */
export interface IssueRequestBuilder extends BaseRequestBuilder<IssueRequestBuilder> {
    /**
     * The create property
     */
    get create(): CreateRequestBuilder;
    /**
     * The list property
     */
    get list(): ListRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const IssueRequestBuilderUriTemplate = "{+baseurl}/issue";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const IssueRequestBuilderNavigationMetadata: Record<Exclude<keyof IssueRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    create: {
        requestsMetadata: CreateRequestBuilderRequestsMetadata,
    },
    list: {
        requestsMetadata: ListRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
