/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePr400Error}
 */
// @ts-ignore
export function createCreatePr400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePr400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePr403Error}
 */
// @ts-ignore
export function createCreatePr403ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePr403Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePr422Error}
 */
// @ts-ignore
export function createCreatePr422ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePr422Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePr500Error}
 */
// @ts-ignore
export function createCreatePr500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePr500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePrPostRequestBody_filesMember1 | CreatePrPostRequestBody_filesMember2}
 */
// @ts-ignore
export function createCreatePrPostRequestBody_filesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePrPostRequestBody_files;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePrPostRequestBody_filesMember1}
 */
// @ts-ignore
export function createCreatePrPostRequestBody_filesMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePrPostRequestBody_filesMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePrPostRequestBody_filesMember2}
 */
// @ts-ignore
export function createCreatePrPostRequestBody_filesMember2FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePrPostRequestBody_filesMember2;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePrPostRequestBody}
 */
// @ts-ignore
export function createCreatePrPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePrPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePrPostResponse_data}
 */
// @ts-ignore
export function createCreatePrPostResponse_dataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePrPostResponse_data;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePrPostResponse}
 */
// @ts-ignore
export function createCreatePrPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePrPostResponse;
}
export interface CreatePr400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreatePr403Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreatePr422Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreatePr500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The data property
     */
    data?: UntypedNode | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreatePrPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The branchName property
     */
    branchName?: string | null;
    /**
     * The commitMessage property
     */
    commitMessage?: string | null;
    /**
     * The files property
     */
    files?: (CreatePrPostRequestBody_filesMember1 | CreatePrPostRequestBody_filesMember2)[] | null;
    /**
     * The prBody property
     */
    prBody?: string | null;
    /**
     * The prTitle property
     */
    prTitle?: string | null;
}
export type CreatePrPostRequestBody_files = CreatePrPostRequestBody_filesMember1 | CreatePrPostRequestBody_filesMember2;
export interface CreatePrPostRequestBody_filesMember1 extends AdditionalDataHolder, Parsable {
    /**
     * The content property
     */
    content?: string | null;
    /**
     * The operation property
     */
    operation?: CreatePrPostRequestBody_filesMember1_operation | null;
    /**
     * The path property
     */
    path?: string | null;
}
export type CreatePrPostRequestBody_filesMember1_operation = (typeof CreatePrPostRequestBody_filesMember1_operationObject)[keyof typeof CreatePrPostRequestBody_filesMember1_operationObject];
export interface CreatePrPostRequestBody_filesMember2 extends AdditionalDataHolder, Parsable {
    /**
     * The operation property
     */
    operation?: CreatePrPostRequestBody_filesMember2_operation | null;
    /**
     * The path property
     */
    path?: string | null;
}
export type CreatePrPostRequestBody_filesMember2_operation = (typeof CreatePrPostRequestBody_filesMember2_operationObject)[keyof typeof CreatePrPostRequestBody_filesMember2_operationObject];
export interface CreatePrPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: CreatePrPostResponse_data[] | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface CreatePrPostResponse_data extends AdditionalDataHolder, Parsable {
    /**
     * The branchName property
     */
    branchName?: string | null;
    /**
     * The commitSha property
     */
    commitSha?: string | null;
    /**
     * The note property
     */
    note?: string | null;
    /**
     * The prNumber property
     */
    prNumber?: number | null;
    /**
     * The prUrl property
     */
    prUrl?: string | null;
}
/**
 * Builds and executes requests for operations under /create-pr
 */
export interface CreatePrRequestBuilder extends BaseRequestBuilder<CreatePrRequestBuilder> {
    /**
     * 指定のブランチにファイル変更をコミットし、Pull Request を作成します。リクエスト:- prTitle: PR のタイトル（必須）- prBody: PR の本文（任意）- branchName: 作成または更新するブランチ名（必須）- commitMessage: コミットメッセージ（任意、未指定時はデフォルト）- files: 変更対象の配列。{ path, content, operation }。operation は upsert|delete。検証/安全性:- path は ensureUserPathSafe によってパス走査などを防止します。応答:- 成功時は prNumber, prUrl, branchName, commitSha, note を含む配列を返します。エラー:- 400: リクエスト不正- 403: 権限不足- 422: 処理不能（内容不整合など）- 500: サーバエラー
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreatePrPostResponse>}
     * @throws {CreatePr400Error} error when the service returns a 400 status code
     * @throws {CreatePr403Error} error when the service returns a 403 status code
     * @throws {CreatePr422Error} error when the service returns a 422 status code
     * @throws {CreatePr500Error} error when the service returns a 500 status code
     */
     post(body: CreatePrPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreatePrPostResponse | undefined>;
    /**
     * 指定のブランチにファイル変更をコミットし、Pull Request を作成します。リクエスト:- prTitle: PR のタイトル（必須）- prBody: PR の本文（任意）- branchName: 作成または更新するブランチ名（必須）- commitMessage: コミットメッセージ（任意、未指定時はデフォルト）- files: 変更対象の配列。{ path, content, operation }。operation は upsert|delete。検証/安全性:- path は ensureUserPathSafe によってパス走査などを防止します。応答:- 成功時は prNumber, prUrl, branchName, commitSha, note を含む配列を返します。エラー:- 400: リクエスト不正- 403: 権限不足- 422: 処理不能（内容不整合など）- 500: サーバエラー
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePrPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The deserialization information for the current model
 * @param CreatePr400Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePr400Error(createPr400Error: Partial<CreatePr400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createPr400Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { createPr400Error.messageEscaped = n.getStringValue(); },
        "success": n => { createPr400Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePr403Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePr403Error(createPr403Error: Partial<CreatePr403Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createPr403Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { createPr403Error.messageEscaped = n.getStringValue(); },
        "success": n => { createPr403Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePr422Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePr422Error(createPr422Error: Partial<CreatePr422Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createPr422Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { createPr422Error.messageEscaped = n.getStringValue(); },
        "success": n => { createPr422Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePr500Error The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePr500Error(createPr500Error: Partial<CreatePr500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createPr500Error.data = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "message": n => { createPr500Error.messageEscaped = n.getStringValue(); },
        "success": n => { createPr500Error.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePrPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePrPostRequestBody(createPrPostRequestBody: Partial<CreatePrPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "branchName": n => { createPrPostRequestBody.branchName = n.getStringValue(); },
        "commitMessage": n => { createPrPostRequestBody.commitMessage = n.getStringValue(); },
        "files": n => { createPrPostRequestBody.files = n.getCollectionOfObjectValues<CreatePrPostRequestBody_filesMember1>(createCreatePrPostRequestBody_filesMember1FromDiscriminatorValue) ?? n.getCollectionOfObjectValues<CreatePrPostRequestBody_filesMember2>(createCreatePrPostRequestBody_filesMember2FromDiscriminatorValue); },
        "prBody": n => { createPrPostRequestBody.prBody = n.getStringValue(); },
        "prTitle": n => { createPrPostRequestBody.prTitle = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePrPostRequestBody_files The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePrPostRequestBody_files(createPrPostRequestBody_files: Partial<CreatePrPostRequestBody_filesMember1 | CreatePrPostRequestBody_filesMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoCreatePrPostRequestBody_filesMember1(createPrPostRequestBody_files as CreatePrPostRequestBody_filesMember1),
        ...deserializeIntoCreatePrPostRequestBody_filesMember2(createPrPostRequestBody_files as CreatePrPostRequestBody_filesMember2),
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePrPostRequestBody_filesMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePrPostRequestBody_filesMember1(createPrPostRequestBody_filesMember1: Partial<CreatePrPostRequestBody_filesMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "content": n => { createPrPostRequestBody_filesMember1.content = n.getStringValue(); },
        "operation": n => { createPrPostRequestBody_filesMember1.operation = n.getEnumValue<CreatePrPostRequestBody_filesMember1_operation>(CreatePrPostRequestBody_filesMember1_operationObject); },
        "path": n => { createPrPostRequestBody_filesMember1.path = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePrPostRequestBody_filesMember2 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePrPostRequestBody_filesMember2(createPrPostRequestBody_filesMember2: Partial<CreatePrPostRequestBody_filesMember2> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "operation": n => { createPrPostRequestBody_filesMember2.operation = n.getEnumValue<CreatePrPostRequestBody_filesMember2_operation>(CreatePrPostRequestBody_filesMember2_operationObject); },
        "path": n => { createPrPostRequestBody_filesMember2.path = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePrPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePrPostResponse(createPrPostResponse: Partial<CreatePrPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { createPrPostResponse.data = n.getCollectionOfObjectValues<CreatePrPostResponse_data>(createCreatePrPostResponse_dataFromDiscriminatorValue); },
        "message": n => { createPrPostResponse.message = n.getStringValue(); },
        "success": n => { createPrPostResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePrPostResponse_data The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePrPostResponse_data(createPrPostResponse_data: Partial<CreatePrPostResponse_data> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "branchName": n => { createPrPostResponse_data.branchName = n.getStringValue(); },
        "commitSha": n => { createPrPostResponse_data.commitSha = n.getStringValue(); },
        "note": n => { createPrPostResponse_data.note = n.getStringValue(); },
        "prNumber": n => { createPrPostResponse_data.prNumber = n.getNumberValue(); },
        "prUrl": n => { createPrPostResponse_data.prUrl = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param CreatePr400Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePr400Error(writer: SerializationWriter, createPr400Error: Partial<CreatePr400Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPr400Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", createPr400Error.data);
    writer.writeStringValue("message", createPr400Error.messageEscaped);
    writer.writeBooleanValue("success", createPr400Error.success);
    writer.writeAdditionalData(createPr400Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePr403Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePr403Error(writer: SerializationWriter, createPr403Error: Partial<CreatePr403Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPr403Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", createPr403Error.data);
    writer.writeStringValue("message", createPr403Error.messageEscaped);
    writer.writeBooleanValue("success", createPr403Error.success);
    writer.writeAdditionalData(createPr403Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePr422Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePr422Error(writer: SerializationWriter, createPr422Error: Partial<CreatePr422Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPr422Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", createPr422Error.data);
    writer.writeStringValue("message", createPr422Error.messageEscaped);
    writer.writeBooleanValue("success", createPr422Error.success);
    writer.writeAdditionalData(createPr422Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePr500Error The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePr500Error(writer: SerializationWriter, createPr500Error: Partial<CreatePr500Error> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPr500Error || isSerializingDerivedType) { return; }
    writer.writeObjectValue("data", createPr500Error.data);
    writer.writeStringValue("message", createPr500Error.messageEscaped);
    writer.writeBooleanValue("success", createPr500Error.success);
    writer.writeAdditionalData(createPr500Error.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePrPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePrPostRequestBody(writer: SerializationWriter, createPrPostRequestBody: Partial<CreatePrPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPrPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeStringValue("branchName", createPrPostRequestBody.branchName);
    writer.writeStringValue("commitMessage", createPrPostRequestBody.commitMessage);
    writer.writeCollectionOfObjectValues<CreatePrPostRequestBody_filesMember1 | CreatePrPostRequestBody_filesMember2>("files", createPrPostRequestBody.files, serializeCreatePrPostRequestBody_files);
    writer.writeStringValue("prBody", createPrPostRequestBody.prBody);
    writer.writeStringValue("prTitle", createPrPostRequestBody.prTitle);
    writer.writeAdditionalData(createPrPostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePrPostRequestBody_files The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePrPostRequestBody_files(writer: SerializationWriter, createPrPostRequestBody_files: Partial<CreatePrPostRequestBody_filesMember1 | CreatePrPostRequestBody_filesMember2> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeCreatePrPostRequestBody_filesMember1(writer, createPrPostRequestBody_files as CreatePrPostRequestBody_filesMember1);
    serializeCreatePrPostRequestBody_filesMember2(writer, createPrPostRequestBody_files as CreatePrPostRequestBody_filesMember2);
}
/**
 * Serializes information the current object
 * @param CreatePrPostRequestBody_filesMember1 The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePrPostRequestBody_filesMember1(writer: SerializationWriter, createPrPostRequestBody_filesMember1: Partial<CreatePrPostRequestBody_filesMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPrPostRequestBody_filesMember1 || isSerializingDerivedType) { return; }
    writer.writeStringValue("content", createPrPostRequestBody_filesMember1.content);
    writer.writeEnumValue<CreatePrPostRequestBody_filesMember1_operation>("operation", createPrPostRequestBody_filesMember1.operation);
    writer.writeStringValue("path", createPrPostRequestBody_filesMember1.path);
    writer.writeAdditionalData(createPrPostRequestBody_filesMember1.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePrPostRequestBody_filesMember2 The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePrPostRequestBody_filesMember2(writer: SerializationWriter, createPrPostRequestBody_filesMember2: Partial<CreatePrPostRequestBody_filesMember2> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPrPostRequestBody_filesMember2 || isSerializingDerivedType) { return; }
    writer.writeEnumValue<CreatePrPostRequestBody_filesMember2_operation>("operation", createPrPostRequestBody_filesMember2.operation);
    writer.writeStringValue("path", createPrPostRequestBody_filesMember2.path);
    writer.writeAdditionalData(createPrPostRequestBody_filesMember2.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePrPostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePrPostResponse(writer: SerializationWriter, createPrPostResponse: Partial<CreatePrPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPrPostResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<CreatePrPostResponse_data>("data", createPrPostResponse.data, serializeCreatePrPostResponse_data);
    writer.writeStringValue("message", createPrPostResponse.message);
    writer.writeBooleanValue("success", createPrPostResponse.success);
    writer.writeAdditionalData(createPrPostResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePrPostResponse_data The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePrPostResponse_data(writer: SerializationWriter, createPrPostResponse_data: Partial<CreatePrPostResponse_data> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPrPostResponse_data || isSerializingDerivedType) { return; }
    writer.writeStringValue("branchName", createPrPostResponse_data.branchName);
    writer.writeStringValue("commitSha", createPrPostResponse_data.commitSha);
    writer.writeStringValue("note", createPrPostResponse_data.note);
    writer.writeNumberValue("prNumber", createPrPostResponse_data.prNumber);
    writer.writeStringValue("prUrl", createPrPostResponse_data.prUrl);
    writer.writeAdditionalData(createPrPostResponse_data.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const CreatePrRequestBuilderUriTemplate = "{+baseurl}/create-pr";
export const CreatePrPostRequestBody_filesMember1_operationObject = {
    Upsert: "upsert",
} as const;
export const CreatePrPostRequestBody_filesMember2_operationObject = {
    Delete: "delete",
} as const;
/**
 * Metadata for all the requests in the request builder.
 */
export const CreatePrRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CreatePrRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createCreatePr400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createCreatePr403ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createCreatePr422ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createCreatePr500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreatePrPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePrPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
